version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1
  path-filtering: circleci/path-filtering@0.1.3

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - path-filtering/set-parameters:
          base-revision: add-cci
          output-path: .circleci/filter-services.json
          mapping: |
            src/balancereader/.* balancereader true
            src/contacts/.* contacts true
            src/ledgerwriter/.* ledgerwriter true
            src/transactionhistory/.* transactionhistory true
            src/userservice/.* userservice true
            .circleci/.* frontend true
      - run:
          name: Generate parameters
          command: python3 .circleci/generate-parameters.py
      - continuation/continue:
          configuration_path: .circleci/continue.yml
          parameters: .circleci/pipeline-parameters.json
      - store_artifacts:
          path: .circleci

workflows:
  setup:
    jobs:
      - setup
